### ISSUE TITLE
Create a todo list

### ISSUE THREAD

**Issue by jagagoda** [jagagoda/TODO-list#2]
MUST HAVE
- [x] add an input to add new todos
- [x] add a button that saves the task with redux
- [x] add a checkbox for the task
- [x] display the tasks on the screen
- [x] add styling to list container
- [x] add styling to input
- [x] add styling to button

SHOULD HAVE
- [x] add a delete button that deletes the task
- [x] add router to edit button
- [x] add an edit button that edits the task
- [x] add styling to buttons

**Comment by jagagoda** [comment]
Done with success :)
